name: Deploy Site to LightSail

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Sync
      run: |
        echo "${{secrets.SSH_KEY}}" > deploy_key
        chmod 600 ./deploy_key
        rsync --rsync-path 'sudo -u ${{secrets.SITE_OWNER}} rsync' -chav --delete \
          -e 'ssh -i ./deploy_key -o StrictHostKeyChecking=no' \
          --exclude /deploy_key \
          --exclude /.gitignore \
          --exclude /.vscode/ \
          --exclude /.git/ \
          --exclude /.github/ \
          --exclude /scss/ \
          ./ ${{secrets.DEST}}